### ISSUE TITLE
Resolving dependencies for nested modules doesn't use appropriate root directory.

### ISSUE THREAD

**Issue by joeandaverde** [rtfeldman/node-elm-compiler#25]
Here's an example:

```
/src
   /Components
      /MyComponent
         MyComponentMain.elm
         View.elm
         Update.elm
         Model.elm
```

MyComponentMain might be defined as
```elm
module Components.MyComponent.MyComponentMain where

import Components.MyComponent.View
import Components.MyComponent.Model
import Components.MyComponent.Update

...
```

Since the main module is located at `src/Components/MyComponent/MyComponentMain.elm` (ie `elm-make src/Components/MyComponent/MyComponentMain.elm`) then all resolved dependencies will be relative to that directory. For example:

```
src/Components/MyComponent/Components/MyComponent/View.elm
src/Components/MyComponent/Components/MyComponent/Model.elm
src/Components/MyComponent/Components/MyComponent/Update.elm
```

Some ideas

1. Search for modules starting at the source directories specified in the nearest `elm-package.json` 
2. Set the base directory starting at (src/Components/MyComponent/)  and moving up N directories where N is the number of `.` in the module name.

**Comment by rtfeldman** [comment]
Sorry I took so long getting to this! I thought about it, and I think the answer is to explicitly pass in the `cwd` argument if you want to run from a different root directory than the directory of the target file.

The first proposed solution won't necessarily work right if there's an `elm-package.json` "lower than expected" (perhaps because you're including an example `elm-package.json` to go with some code, but that's not what you need to compile the whole thing), and the second one relies on the `src` directory being at the root (or one deeper) - so if you have `src/elm/Components` it won't work.

Thanks for the report!
